### ISSUE TITLE
Text content siblings

### ISSUE THREAD

**Issue by caph1993** [kriszyp/put-selector#33]
Hello, is it possible to generate the following tree using `put` syntax?

```html
<div>Hello <b>text</b> world</div>
```
The issue is that the `div` element has two text children, `"Hello "` and `" world"`, but the dollar sign syntax `$` seems to be designed to accept only one.

**Comment by rtasarz** [comment]
Do you mean something like: `put('div $ b $ < $', 'Hello' , 'text', ' world')` ?

**Comment by caph1993** [comment]
Yes, that's exactly what I meant. Thank you.
